#!/bin/bash

# This is the same as the main repo `run` script except that it:
# * mounts the genetic directory
# * uses the genetic Docker image
# * mounts the main RV repo only if it's pointed to by RASTER_VISION_REPO
# * removes the --docs option

set -e

if [[ -n "${RASTER_VISION_DEBUG}" ]]; then
    set -x
fi

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DOCKER_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
REPO_ROOT="$( cd -P "$( dirname "$DOCKER_DIR" )" && pwd )"

function usage() {
    echo -n \
         "Usage: $(basename "$0") <options> <command>
Run a console in the raster-vision-genetic Docker image locally.

Environment variables:
RASTER_VISION_DATA_DIR (directory for storing data; mounted to /opt/data)
AWS_PROFILE (optional AWS profile)
RASTER_VISION_REPO (optional path to main RV repo; mounted to /opt/src)

Options:
--aws forwards AWS credentials (sets AWS_PROFILE env var and mounts ~/.aws to /root/.aws)
--name sets the name of the running container

All arguments after above options are passed to 'docker run'.
"
}

IMAGE="raster-vision-genetic"
RASTER_VISION_DATA_DIR="${RASTER_VISION_DATA_DIR:-${REPO_ROOT}/data}"

# Parse options using scheme in
# https://stackoverflow.com/questions/192249/how-do-i-parse-command-line-arguments-in-bash
POSITIONAL=()
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        --help)
        usage
        exit 0
        shift
        ;;
        --aws)
        AWS="-e AWS_PROFILE=${AWS_PROFILE:-default} -v ${HOME}/.aws:/root/.aws:ro"
        shift # past argument
        ;;
        --name)
        shift
        NAME="--name $1"
        shift
        ;;
        *) # unknown option
        POSITIONAL+=("$1") # save it in an array for later
        shift # past argument
        ;;
    esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [ -z "${CMD}" ]
then
    CMD=(${@:1})
fi

if [ -z "$RASTER_VISION_REPO" ]
then
    RV_SRC_FLAGS=""
else
    RV_SRC_FLAGS="-v ${RASTER_VISION_REPO}/rastervision:/opt/src/rastervision"
fi

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    docker run ${RUNTIME} ${NAME} --rm -it \
        -v "${HOME}"/.rastervision:/root/.rastervision \
        -v "${REPO_ROOT}"/genetic:/opt/src/genetic \
        -v "${REPO_ROOT}"/examples:/opt/src/examples \
        -v ${RASTER_VISION_DATA_DIR}:/opt/data \
        ${DOCS} \
        ${RV_SRC_FLAGS} \
        ${IMAGE} "${CMD[@]}"
fi
